blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: For help on using Github, please ask questions here.
  - name: Chrome Extensions Support
    url: https://developer.chrome.com/docs/extensions/support-feedback/getHelp/
    about: For general browser extensions help, see the chrome support page. 
